# Generated by Django 3.1.6 on 2022-05-11 14:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50, verbose_name='요약')),
                ('description', models.TextField(blank=True, verbose_name='상세설명')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='시작시간')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='완료시간')),
                ('date', models.DateField(verbose_name='일자')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
            ],
        ),
    ]
